version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "JoeyZhouAus"
    assignees:
      - "JoeyZhouAus"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        patterns:
          - "@*"
          - "next"
          - "react*"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "eslint*"
          - "@types/*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "JoeyZhouAus"
    assignees:
      - "JoeyZhouAus"
