name: Deploy to Amplify (IAM Role)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::882062870024:role/GitHubActionsAmplifyRole
        aws-region: ap-southeast-2

    - name: Trigger Amplify Build
      run: |
        aws amplify start-job \
          --app-id d2tmeeiuqjkvzh \
          --branch-name ${{ github.event.inputs.branch }} \
          --job-type RELEASE \
          --commit-message "Triggered from GitHub Actions"
